### ISSUE TITLE
[Building-03] Can load data in BuildingStatus but cannot load the list trạng thái(buildingstatus) for edit the building.

### ISSUE THREAD

**Issue by DungNTHE163886** [VuLHHE163397/SEP490-G71-FA24#16]
https://drive.google.com/file/d/1cE-__vr9okeRNNJRlKfrkbY6S0xDJglz/view?usp=sharing

**Comment by VuLHHE163397** [comment]
để data tiếng Việt đi em, em code cho người VN đọc dùng đấy
